title: Atriva Media Blog
description: Blog for Atriva Media
author: Wesley L.
logo: /hcz-jekyll-blog/static/img/avatar.png
github: #https://github.com/ashutosh2k12
about: Atriva Media - Ultimate Media Solution 

baseurl: "http://blog.atrivamedia.com" # "http://aboutashu.com/hcz-jekyll-blog"
url: "http://blog.atrivamedia.com" # "http://aboutashu.com/hcz-jekyll-blog"

disqus_shortname: #aboutashu
google_analytics: #UA-72862926-1

share:
  twitter_username: \#
  fb_appid: 000000000000


enableTags: true
tagarray: []

paginate: 20
per_page: 20
paginate_path: "/page:num/"
markdown: kramdown
gems: [jekyll-paginate, jekyll-gist]
